name: eeg_hearable
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.7.5=pyhb46e38b_100
  - anaconda-auth=0.12.3=py313h06a4308_0
  - anaconda-cli-base=0.7.0=py313h06a4308_0
  - annotated-types=0.6.0=py313h06a4308_1
  - archspec=0.2.5=pyhd3eb1b0_0
  - boltons=25.0.0=py313h06a4308_0
  - brotlicffi=1.2.0.0=py313h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2026.01.04=py313h06a4308_0
  - cffi=2.0.0=py313h4eded50_1
  - charset-normalizer=3.4.4=py313h06a4308_0
  - click=8.2.1=py313h06a4308_1
  - conda=25.11.1=py313h06a4308_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313h06a4308_1
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.11.0=pyhdf14ebd_0
  - conda-package-handling=2.4.0=py313h06a4308_1
  - conda-package-streaming=0.12.0=py313h06a4308_1
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=46.0.3=py313h0a354b3_0
  - dbus=1.16.2=h5bd4931_0
  - distro=1.9.0=py313h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - filelock=3.20.0=py313h06a4308_0
  - fmt=11.2.0=hca5f364_0
  - frozendict=2.4.6=py313hee96239_0
  - fsspec=2026.1.0=py313h7040dfc_0
  - gettext=0.21.0=hedfda30_2
  - hf-xet=1.1.8=py313h84c0859_0
  - huggingface_hub=0.34.4=py313h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=py313h06a4308_0
  - jansson=2.14=h5eee18b_1
  - jaraco.classes=3.4.0=py313h06a4308_0
  - jaraco.context=6.0.0=py313h06a4308_0
  - jaraco.functools=4.1.0=py313h06a4308_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=3.0.0=py313h06a4308_0
  - keyring=25.7.0=py313h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libarchive=3.8.2=h3ec8f01_0
  - libcurl=8.16.0=heebcbe5_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libmamba=2.3.2=h860b5fb_1
  - libmambapy=2.3.2=py313h3f77f5b_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.1=h697f920_0
  - libsolv=0.7.30=h6f1ccf3_2
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=py313h06a4308_0
  - mdurl=0.1.2=py313h06a4308_0
  - menuinst=2.4.2=py313h06a4308_1
  - more-itertools=10.8.0=py313h06a4308_0
  - msgpack-python=1.1.1=py313h6a678d5_0
  - ncurses=6.5=h7934f7d_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py313h06a4308_1
  - pcre2=10.46=hf426167_0
  - pip=25.3=pyhc872135_0
  - pkce=1.0.3=py313h06a4308_0
  - platformdirs=4.5.0=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.23=py313h06a4308_0
  - pydantic=2.12.4=py313h06a4308_0
  - pydantic-core=2.41.5=py313h498d7c9_1
  - pydantic-settings=2.12.0=py313h06a4308_0
  - pygments=2.19.2=py313h06a4308_0
  - pyjwt=2.10.1=py313h06a4308_1
  - pysocks=1.7.1=py313h06a4308_1
  - python=3.13.11=hcf712cf_100_cp313
  - python-dotenv=1.1.0=py313h06a4308_0
  - python_abi=3.13=3_cp313
  - pyyaml=6.0.3=py313h591646f_0
  - readchar=4.2.1=py313h06a4308_0
  - readline=8.3=hc2a1206_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.5=py313h06a4308_1
  - rich=14.2.0=py313h06a4308_0
  - ruamel.yaml=0.18.16=py313h4aee224_0
  - ruamel.yaml.clib=0.2.14=py313h4aee224_0
  - secretstorage=3.4.0=py313h3e8c6aa_0
  - semver=3.0.4=py313h06a4308_0
  - setuptools=80.9.0=py313h06a4308_0
  - shellingham=1.5.4=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py313h06a4308_0
  - tqdm=4.67.1=py313h7040dfc_1
  - truststore=0.10.1=py313h06a4308_1
  - typer=0.20.0=py313h06a4308_0
  - typer-slim=0.20.0=py313h06a4308_0
  - typer-slim-standard=0.20.0=py313h06a4308_0
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing-inspection=0.4.2=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.1=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.24.0=py313h3d778a8_0
  - zstd=1.5.7=h11fc155_0